name: Neutron Web CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build using Node v18
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install --legacy-peer-deps   
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    name: Test using Node v18
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install --legacy-peer-deps   
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run test
        env:
          CI: true
