name: Neutron Web CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Clone Neutron Core
        run: |
          cd ..
          git clone https://hugoperier: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@github.com/hugoperier/neutron-core
          cd neutron-core
          npm install
          npm link
      - name: Link Neutron Core to Neutron Web
        run: |
          cd ../neutron-web
          npm link neutron-core
      - name: Run Tests
        run: |
          yarn test