name: Neutron Web CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Clone Neutron Core, build then test
        run: |
          echo Install neutron-core
          cd ..
          git clone https://hugoperier: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@github.com/hugoperier/neutron-core
          cd ./neutron-core
          yarn
          yarn tsc
          cd ../neutron-web

          echo Install neutron-web
          yarn

          echo Linking neutron core
          yarn add ../neutron-core
          yarn test
